name: Build MinerSearch Solution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Restore NuGet packages
    - name: Restore NuGet packages
      run: nuget restore MinerSearch (1).sln

    # Build the solution
    - name: Build solution
      run: msbuild "MinerSearch (1).sln" /p:Configuration=Release /p:Platform="Any CPU" /t:rebuild /verbosity:minimal

    # Optional: Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MinerSearch-Build
        path: |
          MinerSearch\bin\Release\
          dbase\bin\Release\
          netlib\bin\Release\
