name: Build MinerSearch Solution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [Any CPU, x64, x86]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Adjust based on project requirements

    - name: Restore NuGet packages
      run: dotnet restore MinerSearch.sln

    - name: Build solution
      run: dotnet build MinerSearch.sln --configuration ${{ matrix.configuration }} --no-restore -p:Platform="${{ matrix.platform }}"
