name: Build MinerSearch

on:
  push:
    branches: [ master ] # Запускать при push в ветку master
  pull_request:
    branches: [ master ] # Запускать также при pull request в ветку master

jobs:
  build:
    runs-on: windows-latest # Использовать последнюю доступную среду Windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Действие для загрузки кода репозитория

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2 # Действие для настройки MSBuild
      # Параметры 'vs-version' и 'msbuild-architecture' здесь не указаны,
      # так как они необязательны и были закомментированы.
      # Если они вам понадобятся, вы можете добавить блок 'with:' см. ниже.

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2 # Действие для настройки NuGet CLI
      with:
        nuget-version: 'latest' # Использовать последнюю версию NuGet

    - name: Restore NuGet packages
      run: nuget restore MinerSearch.sln # Команда для восстановления пакетов для решения MinerSearch.sln
                                         # Убедитесь, что MinerSearch.sln находится в корне репозитория
                                         # или укажи правильный путь к файлу .sln

    - name: Build the application
      run: msbuild MinerSearch.sln /p:Configuration=Release # Команда для сборки решения в конфигурации Release
                                                            # Замени MinerSearch.sln на имя твоего файла решения, если оно другое

    # Опциональный шаг: публикация артефактов сборки (например, .exe файла)
    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: MinerSearch-Build
    #     path: | # Укажи путь к выходным файлам сборки
    #       MinerSearch/bin/Release/MinerSearch.exe
    #       # Добавь другие файлы или папки, если необходимо
